# Generated by Django 4.1.2 on 2022-10-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descriptions',
            field=models.TextField(verbose_name='Descriptions'),
        ),
    ]
